"""Core reproduces its own conformance corpus, on both validate paths.

The corpus (tests/fixtures/conformance/*.jsonl) is generated by
scripts/conformance_fixtures.py with Core as the oracle. These tests keep
Core honest against its own fixtures; any other engine running the OpenDQV
contract format runs the same files and must produce identical verdicts.
See docs/contract_conformance.md.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from opendqv.core.contracts import ContractRegistry
from opendqv.core.rule_parser import Rule
from opendqv.core.validator import (
    _RULE_HANDLERS,
    strict_schema_kwargs,
    validate_batch,
    validate_record,
)

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from conformance_fixtures import _shape, unprobed_rule_types

FIXTURE_DIR = ROOT / "tests" / "fixtures" / "conformance"
FIXTURES = sorted(FIXTURE_DIR.glob("*.jsonl"))


def _load(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _contract_and_rules(name: str):
    reg = ContractRegistry(ROOT / "opendqv" / "contracts")
    contract = reg.get(name)
    assert contract is not None, name
    return contract, reg.get_rules_with_context(contract, None)


def test_corpus_present():
    assert len(FIXTURES) >= 5, "conformance corpus missing — run scripts/conformance_fixtures.py"


def test_every_rule_type_has_a_violation_probe():
    assert not unprobed_rule_types(), f"add these rule types to _VIOLATIONS: {sorted(unprobed_rule_types())}"
    assert set(_RULE_HANDLERS)  # the table is the source of truth, not a hand-kept list


@pytest.mark.parametrize("path", FIXTURES, ids=lambda p: p.stem)
def test_core_reproduces_fixture_on_both_paths(path: Path):
    """Every line: the single-record path and a one-record batch give the recorded verdict."""
    contract, rules = _contract_and_rules(path.stem)
    kw = strict_schema_kwargs(contract, rules)
    for line in _load(path):
        single = _shape(validate_record(line["record"], rules, contract_name=contract.name, **kw))
        assert single == line["expect"], f"{path.stem} single-path drift on {line['record']!r}"
        batch = _shape(validate_batch([line["record"]], rules, contract_name=contract.name, **kw)["results"][0])
        assert batch == line["expect"], f"{path.stem} batch-path drift on {line['record']!r}"


@pytest.mark.parametrize("path", FIXTURES, ids=lambda p: p.stem)
def test_core_reproduces_fixture_as_one_batch(path: Path):
    """The whole corpus as ONE batch gives the same per-record verdicts, except for
    `unique`, whose scope is the batch by definition (a single record can never be
    a duplicate; a corpus full of probe rows sharing the value "x" is)."""
    contract, rules = _contract_and_rules(path.stem)
    kw = strict_schema_kwargs(contract, rules)
    unique_codes = {r.cached_error_code for r in rules if r.type == "unique"}
    lines = _load(path)
    results = validate_batch([line["record"] for line in lines], rules, contract_name=contract.name, **kw)["results"]

    def _strip(exp: dict) -> dict:
        errors = [e for e in exp["errors"] if e["code"] not in unique_codes]
        warnings = [w for w in exp["warnings"] if w["code"] not in unique_codes]
        return {"valid": exp["valid"] if not unique_codes else (not errors), "errors": errors, "warnings": warnings}

    for line, res in zip(lines, results, strict=True):
        assert _strip(_shape(res)) == _strip(line["expect"]), f"{path.stem} full-batch drift on {line['record']!r}"


@pytest.mark.parametrize("path", FIXTURES, ids=lambda p: p.stem)
def test_fixture_proves_acceptance_not_only_rejection(path: Path):
    """Review S5: at least one clean row; a warning-only row where the contract has warning rules."""
    contract, _ = _contract_and_rules(path.stem)
    lines = _load(path)
    by_kind = {k: [line for line in lines if line["kind"] == k] for k in ("clean", "warning_only", "probe")}
    assert by_kind["clean"], f"{path.stem}: no clean row"
    for line in by_kind["clean"]:
        assert line["expect"] == {"valid": True, "errors": [], "warnings": []}
    if any(r.severity.value == "warning" for r in contract.rules):
        assert by_kind["warning_only"], f"{path.stem}: contract has warning rules but no warning-only row"
    for line in by_kind["warning_only"]:
        assert line["expect"]["valid"] is True and line["expect"]["errors"] == [] and line["expect"]["warnings"]
    assert by_kind["probe"]
    assert [line for line in lines if line["kind"] == "blank_probe"], f"{path.stem}: no blank probes (round-2 S1)"


@pytest.mark.parametrize("path", FIXTURES, ids=lambda p: p.stem)
def test_strict_fixture_rejects_undeclared_field(path: Path):
    """Review S4: strict contracts in the corpus carry an __undeclared__ probe that must be rejected."""
    contract, _ = _contract_and_rules(path.stem)
    probe = next(line for line in _load(path) if "__undeclared__" in line["record"])
    codes = {e["code"] for e in probe["expect"]["errors"]}
    if contract.strict_schema:
        assert "OPENDQV_ADDITIONAL_PROPERTIES" in codes and probe["expect"]["valid"] is False
    else:
        assert "OPENDQV_ADDITIONAL_PROPERTIES" not in codes


def test_k1_batch_matches_single_when_field_absent_from_every_record():
    """K1 (review B6): a batch that omits a required field used to validate clean."""
    rules = [Rule(name="a_req", type="not_empty", field="amount", error_message="amount required")]
    single = validate_record({"other": 1}, rules)
    batch = validate_batch([{"other": 1}, {"other": 2}], rules)
    assert single["valid"] is False
    assert [r["valid"] for r in batch["results"]] == [False, False]
    assert batch["results"][0]["errors"][0]["error_code"] == single["errors"][0]["error_code"]



def test_negative_control_a_wrong_expectation_is_detected():
    """Round-2 S1: the comparison must actually bite. Flip one recorded
    verdict in memory and prove the reproduce-check fails on it."""
    path = FIXTURES[0]
    contract, rules = _contract_and_rules(path.stem)
    kw = strict_schema_kwargs(contract, rules)
    line = _load(path)[0]
    tampered = dict(line["expect"], valid=not line["expect"]["valid"])
    single = _shape(validate_record(line["record"], rules, contract_name=contract.name, **kw))
    assert single == line["expect"]
    assert single != tampered
    tampered2 = dict(line["expect"], errors=line["expect"]["errors"] + [{"code": "OPENDQV_FAKE", "severity": "error", "message": "x"}])
    assert single != tampered2
